/**/controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    #dd_controller:
      #type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster




#this is for controller manager to activate
#joint_state_broadcaster:
  #ros__parameters:
    #use_sim_time: true


/**/dd_controller:
  ros__parameters:
    type        : diff_drive_controller/DiffDriveController
    left_wheel_names  : ['left_wheel_joint']     #Names of the left side wheels’ joints
    right_wheel_names : ['right_wheel_joint']    #Names of the right side wheels’ joints

   

    wheel_separation : 0.45
    wheel_radius : 0.10

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    
    odom_frame_id: odom           #odom frame name
    base_frame_id: base_footprint      #Name of the robot’s base frame that is child of the odometry frame.

    pose_covariance_diagonal : [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.0, 0.0, 0.0, 0.01]
 
    enable_odom_tf: true         #Publish transformation between odom_frame_id and base_frame_id.
   

    publish_limited_velocity: true
    publish_wheel_data: true
  

 
 
    open_loop: true  # use false if you want odometry from Gazebo wheel feedback
    cmd_vel_timeout: 0.5
   
    use_stamped_vel: false


    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 1.0
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.max_velocity: 1.0
    angular.z.min_velocity: -1.0
    angular.z.max_acceleration: 1.0
    angular.z.min_acceleration: -1.0
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN

    cmd_vel:
      topic: /cmd_vel 



    
  

  


